export { default as Header } from './Header/Header'
export { default as AboutUs } from './AboutUs/AboutUs'
export { default as Experience } from './Experience/Experience'
export { default as Team } from './Team/Team'
export { default as Work } from './Work/Work'